### ISSUE TITLE
What's the difference between package-updates and security-updates?

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/security-updates#1]
Hey Jamie,

Is there a difference between this and package-updates? Should we deprecate security-updates and make it all standard in Webmin?

**Comment by swelljoe** [comment]
Actually, it looks like it has been deprecated and package-updates is the replacement. So, we don't even need to be installing security-updates, anymore, right?

**Comment by swelljoe** [comment]
Actually (again), it looks like security-updates is still linked in some places. So, they seem identical or similar in purpose and use, but it's up to the caller to determine which one gets opened? Seems like there's some work to be done to remove security-updates.

**Comment by jcameron** [comment]
Yeah, the `package-updates` module has effectively deprecated `security-updates` . I'll check and see if we can stop installing it as part of new Virtualmin installs.

**Comment by jcameron** [comment]
Good news - I've made a bunch of Virtualmin / Cloudmin changes for the next release that will remove the need to install this module. And I've updated our installers to stop installing it by default.
